# Write apps/web/.env.local and apps/mobile/.env from `supabase status -o env`.
[ -n "${CLEAT_ENV_LOADED:-}" ] && return 0
CLEAT_ENV_LOADED=1

_CLEAT_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$_CLEAT_ENV_DIR/common.sh"
# shellcheck source=lan.sh
source "$_CLEAT_ENV_DIR/lan.sh"

cleat_keep() {
  local file="$1"
  local key="$2"
  if [ -f "$file" ]; then
    cleat_status_get "$key" "$file"
    return 0
  fi
  printf '%s' ""
}

cleat_keep_or() {
  local file="$1"
  local key="$2"
  local fallback="$3"
  local current=""
  current="$(cleat_keep "$file" "$key")"
  if [ -n "$current" ]; then
    printf '%s' "$current"
    return 0
  fi
  printf '%s' "$fallback"
}

cleat_append_opt() {
  local key="$1"
  local val="$2"
  if [ -n "$val" ]; then
    printf '%s=%s\n' "$key" "$(cleat_dotenv_quote "$val")"
  fi
}

cleat_write_env() {
  local status_file="$1"
  local root
  root="$(cleat_repo_root)"
  local api=""
  local anon=""
  local service=""
  api="$(cleat_status_get API_URL "$status_file")"
  anon="$(cleat_status_get ANON_KEY "$status_file")"
  service="$(cleat_status_get SERVICE_ROLE_KEY "$status_file")"
  if [ -z "$api" ] || [ -z "$anon" ] || [ -z "$service" ]; then
    echo "supabase status did not include API_URL, ANON_KEY, and SERVICE_ROLE_KEY." >&2
    return 1
  fi

  mkdir -p "$root/apps/web" "$root/apps/mobile"
  local web_file="$root/apps/web/.env.local"
  local mobile_file="$root/apps/mobile/.env"
  local lan=""
  lan="$(cleat_lan_ip)"
  local desk_port="${CLEAT_DESK_PORT:-3000}"
  local mobile_api=""
  mobile_api="$(cleat_url_for_lan "$api" "$lan")"
  local desk_url="http://${lan}:${desk_port}"

  local client_url=""
  local ics=""
  local openai=""
  local inbox=""
  local google_id=""
  local google_secret=""
  client_url="$(cleat_keep_or "$web_file" NEXT_PUBLIC_CLIENT_APP_URL "http://localhost:8081")"
  ics="$(cleat_keep_or "$web_file" ICS_FEED_SIGNING_SECRET "cleat-demo-ics-secret")"
  openai="$(cleat_keep "$web_file" OPENAI_API_KEY)"
  inbox="$(cleat_keep "$web_file" INBOX_UNANSWERED_HOURS)"
  google_id="$(cleat_keep "$web_file" GOOGLE_CLIENT_ID)"
  google_secret="$(cleat_keep "$web_file" GOOGLE_CLIENT_SECRET)"

  local web_tmp=""
  local mobile_tmp=""
  web_tmp="$(mktemp "${web_file}.XXXXXX")"
  mobile_tmp="$(mktemp "${mobile_file}.XXXXXX")"

  {
    echo "# Generated by pnpm run setup. Running it again refreshes Supabase keys and keeps local secrets."
    printf 'NEXT_PUBLIC_SUPABASE_URL=%s\n' "$(cleat_dotenv_quote "$api")"
    printf 'NEXT_PUBLIC_SUPABASE_ANON_KEY=%s\n' "$(cleat_dotenv_quote "$anon")"
    printf 'NEXT_PUBLIC_CLIENT_APP_URL=%s\n' "$(cleat_dotenv_quote "$client_url")"
    printf 'SUPABASE_URL=%s\n' "$(cleat_dotenv_quote "$api")"
    printf 'SUPABASE_SERVICE_ROLE=%s\n' "$(cleat_dotenv_quote "$service")"
    printf 'ICS_FEED_SIGNING_SECRET=%s\n' "$(cleat_dotenv_quote "$ics")"
    cleat_append_opt OPENAI_API_KEY "$openai"
    cleat_append_opt INBOX_UNANSWERED_HOURS "$inbox"
    cleat_append_opt GOOGLE_CLIENT_ID "$google_id"
    cleat_append_opt GOOGLE_CLIENT_SECRET "$google_secret"
  } >"$web_tmp"

  {
    echo "# Generated by pnpm run setup. Running it again refreshes Supabase keys and keeps local secrets."
    printf 'EXPO_PUBLIC_SUPABASE_URL=%s\n' "$(cleat_dotenv_quote "$mobile_api")"
    printf 'EXPO_PUBLIC_SUPABASE_ANON_KEY=%s\n' "$(cleat_dotenv_quote "$anon")"
    printf 'EXPO_PUBLIC_DESK_URL=%s\n' "$(cleat_dotenv_quote "$desk_url")"
    printf 'EXPO_PUBLIC_WEB_URL=%s\n' "$(cleat_dotenv_quote "$desk_url")"
  } >"$mobile_tmp"

  if grep -E -q '^(export[[:space:]]+)?(SERVICE_ROLE_KEY|SUPABASE_SERVICE_ROLE)=' "$mobile_tmp"; then
    rm -f "$web_tmp" "$mobile_tmp"
    echo "Refusing to write the service role into apps/mobile/.env." >&2
    return 1
  fi

  mv "$web_tmp" "$web_file"
  mv "$mobile_tmp" "$mobile_file"
  echo "Wrote apps/web/.env.local"
  echo "Wrote apps/mobile/.env"
  echo "Mobile Supabase URL: ${mobile_api}"
}

# Point the phone at the desk port dev actually bound.
cleat_set_mobile_desk_port() {
  local file="$1"
  local port="$2"
  if [ ! -f "$file" ]; then
    echo "Missing ${file}." >&2
    return 1
  fi
  local tmp=""
  local changed=0
  tmp="$(mktemp)"
  local line=""
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      EXPO_PUBLIC_DESK_URL=* | EXPO_PUBLIC_WEB_URL=*)
        local key="${line%%=*}"
        local raw="${line#*=}"
        local val=""
        local updated=""
        val="$(cleat_unquote "$raw")"
        updated="$(cleat_url_set_port "$val" "$port")"
        if [ "$updated" != "$val" ]; then
          changed=1
        fi
        printf '%s=%s\n' "$key" "$(cleat_dotenv_quote "$updated")"
        ;;
      *)
        printf '%s\n' "$line"
        ;;
    esac
  done <"$file" >"$tmp"
  mv "$tmp" "$file"
  if [ "$changed" -eq 1 ]; then
    echo "Updated apps/mobile/.env desk URLs to port ${port}."
  fi
}
